/**
 * Pure markdown rendering. No clock, no IO: `today` arrives as a parameter so
 * the same corpus renders byte-identically every run, which is the property
 * reconcile relies on to skip unchanged files.
 */
import type { Fact } from "@shared/types.js";
import type { PageRollup, RenderedPage, WikiConfig } from "./types.js";
import { slugify } from "./slug.js";

const LOG_LIMIT = 100;

export function renderPage(page: PageRollup, config: WikiConfig, today: string): RenderedPage {
  const lines: string[] = [
    "---",
    `title: ${page.subject}`,
    "nlm_generated: true",
    `last_projected: ${today}`,
    `fact_count: ${page.current.length}`,
    `session_count: ${page.sessionIds.length}`,
    `superseded_count: ${page.superseded.length}`,
    ...(page.aliases.length > 0
      ? [`aliases: [${page.aliases.map((a) => JSON.stringify(a)).join(", ")}]`]
      : []),
    "---",
    "",
    `> Generated by NLM from ${page.sessionIds.length} session${page.sessionIds.length === 1 ? "" : "s"}.`,
    "> Edits are overwritten. To keep something here, promote it.",
    "",
    "## Current",
    "",
  ];

  for (const f of page.current) {
    lines.push(`- ${f.predicate}: ${f.value}  ^${f.id}`);
    lines.push(`  <sup>[session](${config.linkBase}/thread/${f.sourceSessionId}) · confidence ${f.confidence}</sup>`);
  }
  lines.push("");

  if (page.superseded.length > 0) {
    lines.push("## History", "");
    for (const f of page.superseded) {
      lines.push(`- ~~${f.predicate}: ${f.value}~~ <sup>superseded, from [session](${config.linkBase}/thread/${f.sourceSessionId})</sup>`);
    }
    lines.push("");
  }

  if (page.related.length > 0) {
    lines.push("## Related", "");
    lines.push(page.related.map((s) => `[[${slugify(s)}]]`).join(" · "));
    lines.push("");
  }

  return { relPath: `${page.slug}.md`, content: lines.join("\n") };
}

export function renderIndex(pages: ReadonlyArray<PageRollup>, today: string): RenderedPage {
  const lines: string[] = [
    "---",
    "title: Index",
    "nlm_generated: true",
    `last_projected: ${today}`,
    "---",
    "",
    `> Generated by NLM. ${pages.length} page${pages.length === 1 ? "" : "s"}.`,
    "",
  ];
  const sorted = pages.slice().sort((a, b) => a.subject.localeCompare(b.subject));
  for (const p of sorted) {
    lines.push(`- [[${p.slug}]] <sup>${p.current.length} facts · ${p.sessionIds.length} sessions</sup>`);
  }
  lines.push("");
  return { relPath: "index.md", content: lines.join("\n") };
}

export function renderLog(pages: ReadonlyArray<PageRollup>, today: string): RenderedPage {
  const entries: Array<{ fact: Fact; page: PageRollup }> = [];
  for (const p of pages) for (const f of p.current) entries.push({ fact: f, page: p });
  entries.sort(
    (a, b) => b.fact.createdAt.localeCompare(a.fact.createdAt) || a.fact.id.localeCompare(b.fact.id),
  );

  const lines: string[] = [
    "---",
    "title: Log",
    "nlm_generated: true",
    `last_projected: ${today}`,
    "---",
    "",
    "> Generated by NLM, most recent knowledge at the top.",
    "",
  ];
  for (const { fact, page } of entries.slice(0, LOG_LIMIT)) {
    lines.push(`- ${fact.createdAt.slice(0, 10)} [[${page.slug}]] ${fact.predicate}: ${fact.value}`);
  }
  lines.push("");
  return { relPath: "log.md", content: lines.join("\n") };
}

export function renderAll(
  pages: ReadonlyArray<PageRollup>,
  config: WikiConfig,
  today: string,
): ReadonlyArray<RenderedPage> {
  return [...pages.map((p) => renderPage(p, config, today)), renderIndex(pages, today), renderLog(pages, today)];
}
