/**
 * Filesystem WikiWriter.
 *
 * The ownership check is the load-bearing part. NLM regenerates this tree and
 * deletes files that no longer qualify, so pointing it at a directory a human
 * writes into would destroy their work. A root is writable only when it is
 * absent, empty, or already carries this writer's sentinel. Adoption of a
 * directory holding any other entry is refused, and that includes
 * subdirectories: a nested folder is evidence of a human layout, not of a
 * prior run, because this writer never creates one.
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, relative, isAbsolute } from "node:path";
import type { WikiWriter } from "@ports/wiki-writer.js";

export const SENTINEL_FILE = "AGENTS.md";

/**
 * Adoption requires this marker inside the sentinel body, not just the
 * sentinel's filename. AGENTS.md is now a widely used human/agent
 * convention file on its own, so a directory holding someone else's
 * AGENTS.md alongside their own notes must be refused, not silently
 * adopted and later garbage-collected by reconcile.
 */
export const SENTINEL_MARKER = "<!-- nlm-generated-wiki -->";

export class WikiOwnershipError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "WikiOwnershipError";
  }
}

export class FsWikiWriter implements WikiWriter {
  private readonly root: string;
  private ensured = false;

  constructor(root: string) {
    this.root = resolve(root);
  }

  private resolveWithin(relPath: string): string {
    const full = resolve(this.root, relPath);
    const rel = relative(this.root, full);
    if (rel === "" || rel.startsWith("..") || isAbsolute(rel)) {
      throw new WikiOwnershipError(`path escapes the wiki root: ${relPath}`);
    }
    return full;
  }

  /**
   * Runs the expensive adoption scan once per instance, then writes the
   * sentinel so the root is provably owned before any content write. The
   * scan itself is not repeated on later calls — that cost is paid once per
   * writer, matching the daemon's one-writer-per-run lifecycle.
   */
  private ensureOwned(): void {
    if (this.ensured) {
      return;
    }
    if (!existsSync(this.root)) {
      mkdirSync(this.root, { recursive: true });
    } else {
      const entries = readdirSync(this.root);
      if (entries.length > 0 && !this.hasMarkedSentinel(entries)) {
        throw new WikiOwnershipError(
          `refusing to write into ${this.root}: it holds ${entries.length} entr` +
            `${entries.length === 1 ? "y" : "ies"} and no ${SENTINEL_FILE} carrying the ` +
            `NLM marker, so it is not a directory NLM owns`,
        );
      }
    }
    const sentinel = join(this.root, SENTINEL_FILE);
    if (!existsSync(sentinel)) {
      writeFileSync(sentinel, SENTINEL_BODY, "utf8");
    }
    this.ensured = true;
  }

  /**
   * Adoption-time check only: a sentinel FILE named AGENTS.md is not enough
   * evidence of ownership on its own, since that filename is now a common
   * human/agent convention file a directory might carry for unrelated
   * reasons. Its BODY must also carry SENTINEL_MARKER.
   */
  private hasMarkedSentinel(entries: ReadonlyArray<string>): boolean {
    if (!entries.includes(SENTINEL_FILE)) return false;
    const body = readFileSync(join(this.root, SENTINEL_FILE), "utf8");
    return body.includes(SENTINEL_MARKER);
  }

  /**
   * Cheap re-check for every destructive call after the one-time adoption
   * scan. If a human deletes the sentinel mid-run, this is what stops the
   * rest of that run's writes and removes rather than trusting the stale
   * `ensured` latch.
   */
  private verifySentinelPresent(): void {
    if (!existsSync(join(this.root, SENTINEL_FILE))) {
      throw new WikiOwnershipError(
        `refusing to modify ${this.root}: its ${SENTINEL_FILE} sentinel is gone, ` +
          `so it may no longer be owned by NLM`,
      );
    }
  }

  async write(relPath: string, content: string): Promise<void> {
    this.ensureOwned();
    this.verifySentinelPresent();
    const full = this.resolveWithin(relPath);
    writeFileSync(full, content, "utf8");
  }

  async read(relPath: string): Promise<string | null> {
    const full = this.resolveWithin(relPath);
    if (!existsSync(full)) return null;
    return readFileSync(full, "utf8");
  }

  async remove(relPath: string): Promise<void> {
    this.ensureOwned();
    this.verifySentinelPresent();
    rmSync(this.resolveWithin(relPath), { force: true });
  }

  async list(): Promise<ReadonlyArray<string>> {
    if (!existsSync(this.root)) return [];
    return readdirSync(this.root, { withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.endsWith(".md") && entry.name !== SENTINEL_FILE)
      .map((entry) => entry.name);
  }
}

const SENTINEL_BODY = `${SENTINEL_MARKER}
# Generated by NLM

Every file in this directory is projected from NLM's session corpus and is
rewritten on each projection run. Edits made here are overwritten without
warning.

To keep something, promote it. Promotion copies the content into a page you
own, outside this directory, which NLM never touches.

This file also marks the directory as NLM-owned. Deleting it makes NLM refuse
to write here until the directory is empty again.
`;
